FROM golang:alpine
WORKDIR "/app"
# copy in dep manifests
COPY go.mod go.sum ./
# download dep files
RUN go mod download
# copy in the src code
COPY . .
# build the go app
RUN go build -o app .
CMD ["./app"]