FROM golang:alpine AS build
WORKDIR "/app"
# copy in dep manifests
COPY go.mod go.sum ./
# download dep files
RUN go mod download
# copy in the src code
COPY . .
# build the go app
RUN go build -o app .
#RUN go install main.go

FROM alpine:latest
WORKDIR "/app"
COPY --from=build "./app/app" .
CMD ["./app"]