FROM mongo
COPY locations.json locations.json
#RUN "mongoimport --db=ustrending --collection=locations --file=locations.json  --jsonArray"
CMD ["mongoimport", "--db=ustrending", "--collection=locations", "--file=locations.json", "--jsonArray"]