apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-client
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.2"
            limits:
              memory: "256Mi"
              cpu: "0.2"
          ports:
            - containerPort: 3000
          env:
            # build config
            - name: CI
              value: "true"
            - name: NEXT_PUBLIC_APP_NAME
              value: "US Trending"
            # used on the server-side
            - name: API_URI
              value: "http://public-api-cluster-ip-service:3000"
            # used on the client-side
            - name: NEXT_PUBLIC_API_URI
              value: "http://localhost:8080/api"

