apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: client
  template:
    metadata:
      labels:
        component: client
    spec:
      containers:
        - name: client
          image: your-docker-id/ustrending-client
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.2"
            limits:
              memory: "1Gi"
              cpu: "0.2"
          ports:
            - containerPort: 3000
          env:
            # build config
            - name: CI
              value: "true"
            # used on the server-side
            - name: API_URI
              value: "http://public-api-cluster-ip-service:3000"
            # used on both the client-side and server-side
            - name: NEXT_PUBLIC_APP_NAME
              value: "US Trending"
            - name: NEXT_PUBLIC_API_URI
              value: "http://localhost:8080/api"
            - name: NEXT_PUBLIC_MAX_NUM_GOOGLE_REGION_TRENDS
              value: "15"
            - name: NEXT_PUBLIC_MAX_NUM_SELECTED_REGIONS
              value: "5"
            - name: NEXT_PUBLIC_DEFAULT_NUM_TRENDS_TO_SHOW
              value: "15"

