apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: private-api
  template:
    metadata:
      labels:
        component: private-api
    spec:
      containers:
        - name: private-api
          image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-private-api
          resources:
            requests:
              memory: "256Mi"
              cpu: "0.1"
            limits:
              memory: "256Mi"
              cpu: "0.1"
          ports:
            - containerPort: 3000
          env:
            # redis config
            - name: REDIS_DAILY_TRENDS_KEY
              value: "daily"
            - name: REDIS_DAILY_TRENDS_BY_STATE_KEY
              value: "daily-state"
            - name: REDIS_REALTIME_TRENDS_BY_STATE_KEY
              value: "realtime-state"
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_RECONNECT_ATTEMPTS
              value: "10"
            # mongo db config
            - name: MONGO_HOST
              value: mongo-cluster-ip-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: ""
            - name: MONGO_PASSWORD
              value: ""
            - name: MONGO_DB
              value: ustrending

