apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api-go-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: public-api-go
  template:
    metadata:
      labels:
        component: public-api-go
    spec:
      containers:
        - name: public-api-go
          image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-public-api-go
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.25"
            limits:
              memory: "1Gi"
              cpu: "0.25"
          ports:
            - containerPort: 3000
          env:
            # private api config
            - name: PRIVATE_API_HOST
              value: private-api-cluster-ip-service.default.svc.cluster.local
            - name: PRIVATE_API_PORT
              value: "3000"
            # redis config
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_RECONNECT_ATTEMPTS
              value: "10"
            # mongo db config
            - name: MONGO_HOST
              value: mongo-cluster-ip-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: ""
            - name: MONGO_PASSWORD
              value: ""
            - name: MONGO_DB
              value: ustrending
