apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: public-api
  template:
    metadata:
      labels:
        component: public-api
    spec:
      containers:
        - name: public-api
          image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-public-api
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 3000
          env:
            # redis config
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_RECONNECT_ATTEMPTS
              value: "10"
