apiVersion: apps/v1
kind: Deployment
metadata:
  name: trends-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: trends-api
  template:
    metadata:
      labels:
        component: trends-api
    spec:
      containers:
        - name: trends-api
          image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-trends-api
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.25"
            limits:
              memory: "1Gi"
              cpu: "0.25"
          ports:
            - containerPort: 3000
          env:
            # redis config
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: REDIS_RECONNECT_ATTEMPTS
              value: "10"
            # mongo db config
            - name: MONGO_HOST
              value: mongo-cluster-ip-service
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_USERNAME
              value: ""
            - name: MONGO_PASSWORD
              value: ""
            - name: MONGO_DB
              value: ustrending
