apiVersion: skaffold/v2beta14
kind: Config
build:
  local:
    push: false
  # tell skaffold to overwrite previously built images (should save disk space)
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: your-docker-id/ustrending-public-api
      context: ../public-api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
    - image: your-docker-id/ustrending-trends-api
      context: ../trends-api
      docker:
        dockerfile: Dockerfile.dev
    - image: your-docker-id/ustrending-worker-trends
      context: ../worker-trends
      docker:
        dockerfile: Dockerfile.dev
    - image: your-docker-id/ustrending-client
      context: ../client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - '**/*.js'
          - '**/*.jsx'
          - '**/*.ts'
          - '**/*.tsx'
          - '**/*.css'
          - '**/*.scss'
          - '**/*.html'
    - image: your-docker-id/ustrending-redis
      context: ../redis
      docker:
        dockerfile: Dockerfile.dev
    - image: your-docker-id/ustrending-mongodb
      context: ../mongodb
      docker:
        dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
    - ../k8s/dev/*.yml