apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-public-api
      context: ../public-api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '***/*.js': .
    - image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-client
      context: ../client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '***/*.js': .
        '***/*.css': .
        '***/*.scss': .
        '***/*.html': .
    - image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-worker-google
      context: ../worker-google
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '***/*.js': .
deploy:
  kubectl:
    manifests:
    - ../k8s/dev/*.yml