apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  # tell skaffold to overwrite previously built images (should save disk space)
  tagPolicy:
    gitCommit: {}
  artifacts:
    - image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-public-api
      context: ../public-api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '***/*.js': .
    - image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-private-api
      context: ../private-api
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '***/*.js': .
    - image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-trends-api
      context: ../trends-api
      docker:
        dockerfile: Dockerfile.dev
    - image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-worker-trends
      context: ../worker-trends
      docker:
        dockerfile: Dockerfile.dev
    - image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-client
      context: ../client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        '***/*.js': .
        '***/*.css': .
        '***/*.scss': .
        '***/*.html': .
    # - image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-worker-twitter-trends
    #   context: ../worker-twitter-trends
    #   docker:
    #     dockerfile: Dockerfile.dev
    #   sync:
    #     '***/*.js': .
    - image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-redis
      context: ../redis
      docker:
        dockerfile: Dockerfile.dev
    - image: REPLACE_ME_WITH_YOUR_DOCKER_ID/ustrending-mongodb
      context: ../mongodb
      docker:
        dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
    - ../k8s/dev/*.yml